site_homepage:
    path:     /
    defaults: { _controller: RokkaValidFormsBundle:Default:index }

site_newuser:
    path:      /user/new
    defaults: { _controller: RokkaValidFormsBundle:Default:user }


task_success:
    path:     /success
    defaults: { _controller: RokkaValidFormsBundle:Default:success }

site_newpost:
    path:     /post/new
    defaults: { _controller: RokkaValidFormsBundle:Default:post }
