site_homepage:
    path:     /
    defaults: { _controller: RokkaValidFormsBundle:Default:index }

site_newUser:
    path:      /user/new
    defaults: { _controller: RokkaValidFormsBundle:Default:user }


task_success:
    path:     /success
    defaults: { _controller: RokkaValidFormsBundle:Default:success }
